# Generated by Django 4.2.7 on 2024-03-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='image_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
