# Generated by Django 4.2.7 on 2024-03-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_itemimage_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
