# Generated by Django 4.2.7 on 2024-03-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_paymentinformation_shippingaddress_payment_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinformation',
            name='card_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
